kind: Deployment
apiVersion: apps/v1
metadata:
  name: bashim-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bashim-bot
      id: "bashim-bot"
  template:
    metadata:
      labels:
        app: bashim-bot
        id: "bashim-bot"
    spec:
      containers:
        - name: bashim-bot
          image: alekseinovikov/bashim-bot:latest
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: "bashim-bot-postgresql-db-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "bot_db"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "123456"
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot-token
                  key: bot-token
